### ISSUE TITLE
Locking inside the processBlock callback, is it really ok?

### ISSUE THREAD

**Issue by giohappy** [madskjeldgaard/Birdhouse#48] opened 2024-08-24 20:58 UTC
@madskjeldgaard while reviewing your code I noticed that you lock the `BridgeMidiBufferManager.mInternalBuffer` for writing (from the OSC thread) and reading (from the processBlock). 
I'm not an expert with Juce, so my doubt is more a question: isn't locking that critical section inside the audio callback dangerous? AFAIK no locking should be performed within the `processBlock` (actually any call that could potentially block the callback should be avoided).

**Comment by madskjeldgaard** [comment] 2024-08-26 09:49
Hi @giohappy thanks for your issue! Yes you're exactly right. Locking is dangerous there, but as the code is now I could not figure out how to avoid data races in the situation without locking. It would be really great to have it fixes  ASAP.

I am closing this issue because it's a duplicate of https://github.com/madskjeldgaard/Birdhouse/issues/35 but let's keep the discussion going. Would be best to fix this. 

Thanks again <3

**Closed as completed by madskjeldgaard** 2024-08-26 09:49 UTC
